- name: motd for ubuntu
  when: ansible_facts.distribution == 'Ubuntu'
  block:
    - name: Update motd header
      ansible.builtin.template:
        src: 00-header.j2
        dest: /etc/update-motd.d/00-header

    - name: Remove other default banners
      ansible.builtin.file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
      - 10-help-text
      - 50-motd-news
      - 50-landscape-sysinfo
      - 88-esm-announce
      - 91-contract-ua-esm-status
      - 91-release-upgrade