all:
  children:
    test:
      hosts:
        ru-test-01:
          ansible_host: 192.168.120.129
          ansible_user: andrei
        ru-test-02:
          ansible_host: 192.168.120.128
          ansible_user: root