- name: Configure timesync
  ansible.builtin.template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
  notify: Restart systemd-timesyncd

- name: Enable NTP
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: yes
    state: started

- name: Set timezone to Moscow
  community.general.timezone:
    name: "Europe/Moscow"