- name: Add pritunl repo
  ansible.builtin.template:
    src: pritunl.list.j2
    dest: /etc/apt/sources.list.d/pritunl.list

- name: Add pritunl repo keys
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 7568D9BB55FF9E5287D586017AE645C0CF8E292A

- name: Add nginx repo
  ansible.builtin.template:
    src: nginx.list.j2
    dest: /etc/apt/sources.list.d/nginx.list

- name: Add nginx repo keys
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: ABF5BD827BD9BF62

- name: Install packages
  apt:
    update_cache: yes
    name:
    - nginx
    - pritunl

- name: Retrieve DB password
  hashivault_read:
    mount_point: yandex_db
    secret: Office-MongoDB
    key: pritunl
    version: 2
  register: db_password
  delegate_to: localhost
  become: no
  no_log: true

- name: DB Connection string
  ansible.builtin.template:
    src: pritunl.conf.j2
    dest: /etc/pritunl.conf
  notify: Restart pritunl

- name: Set iptables fact
  ansible.builtin.set_fact:
    rules_nat:  "{{ rules_nat + [lookup('template', 'templates/rules_nat.v4.j2')] }}"
    rules_filter: "{{ rules_filter + [lookup('template', 'templates/rules.v4.j2')] }}"

- name: Remove pritunl rules template
  ansible.builtin.template:
    src: iptables_cron.j2
    dest: /etc/cron.d/iptables_cron

- name: Add external table
  ansible.builtin.template:
    src: rt_tables.j2
    dest: /etc/iproute2/rt_tables
  notify: Netplan apply

- name: Set routes for external table
  ansible.builtin.template:
    src: 60-external-route-table.yaml.j2
    dest: /etc/netplan/60-external-route-table.yaml
  notify: Netplan apply
    
- name: Create nginx configuration
  ansible.builtin.template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  notify: Reload nginx

- name: Disable default site
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Reload nginx

- name: Create ssl directory
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory

- name: Enable startup and start
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
  - nginx
  - pritunl
