- name: Copy YandexInternalRootCA certificate
  ansible.builtin.template:
    src: YandexInternalRootCA.crt
    dest: /usr/local/share/ca-certificates/YandexInternalRootCA.crt
  notify: Update certificates

- name: Copy YandexCLCA certificate
  ansible.builtin.template:
    src: YandexCLCA.crt
    dest: /usr/local/share/ca-certificates/YandexCLCA.crt
  notify: Update certificates