- name: Restart chronyd
  ansible.builtin.systemd:
    state: restarted
    name: chronyd

- name: Restart Restart systemd-timesyncd
  ansible.builtin.systemd:
    state: restarted
    name: systemd-timesyncd